name: build-docker

on:
  push:
    branches: [ dev ]
    paths:
    - debian/Dockerfile

permissions:
  packages: write

jobs:
  build-docker:
    strategy:
      fail-fast: false
      matrix:
        include:
        - { img: ubuntu, tag: focal, file: debian/Dockerfile.focal }
        - { img: ubuntu, tag: noble }
        - { img: debian, tag: bookworm }
        tag: [ focal, noble, bookworm ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: debian
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        context: debian
        file: ${{ matrix.file }}
        push: true
        provenance: false
        platforms: linux/amd64
        tags: ghcr.io/${{ github.repository_owner }}/build:${{ matrix.img }}-${{ matrix.tag }}
        build-args: |
          IMG=${{ matrix.img }}
          TAG=${{ matrix.tag }}