name: macos-dylib

on:
  push:
    tags: [ macos-dylib ]
    paths: [ scripts/macos/* ]

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - tag: Silicon
          arch: arm64
          target: "11.0"
          ffmpeg: "--disable-x86asm"
          meson: --cross-file $GITHUB_WORKSPACE/scripts/macos/macos_arm64.txt
        - tag: Intel
          arch: x86_64
          target: "10.15"
          meson: --cross-file $GITHUB_WORKSPACE/scripts/macos/macos_x86_64.txt
        - tag: Intel_Old
          arch: x86_64
          target: "10.11"
          meson: --cross-file $GITHUB_WORKSPACE/scripts/macos/macos_10.11.txt
        tag: [ Silicon, Intel, Intel_Old ]
    runs-on: macos-latest
    env:
      CMAKE_PREFIX_PATH: /tmp
      PKG_CONFIG_LIBDIR: /tmp/lib/pkgconfig
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: scripts
    - name: Remove stray upstream python binary symlinks under /usr/local
      run: |
        find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -delete -print
        brew unlink python && brew link --overwrite python
    - name: Install dependency
      run: brew reinstall ninja nasm meson
    - name: Build bootstrap
      if: ${{ matrix.tag == 'Intel_Old' }}
      run: |
        curl --retry 5 -sSL https://boostorg.jfrog.io/artifactory/main/release/1.85.0/source/boost_1_85_0.tar.gz | tar zxf - -C ${{ runner.temp }}
        cd ${{ runner.temp }}/boost_1_85_0
        ./bootstrap.sh --with-libraries=filesystem --without-icu -prefix=$CMAKE_PREFIX_PATH
        ./b2 install target-os=darwin variant=release --with-filesystem \
          cxxflags="-arch ${{ matrix.arch }} -mmacosx-version-min=${{ matrix.target }}" \
          linkflags="-arch ${{ matrix.arch }} -mmacosx-version-min=${{ matrix.target }}"
    - name: Build glfw
      run: |
        curl --retry 5 -sSL https://github.com/dragonflylee/glfw/archive/switchfin.tar.gz | tar zxf - -C ${{ runner.temp }}
        cmake -P ${{ runner.temp }}/glfw-switchfin/CMake/GenerateMappings.cmake \
          ${{ runner.temp }}/glfw-switchfin/src/mappings.h.in \
          ${{ runner.temp }}/glfw-switchfin/src/mappings.h

        cmake -B build-glfw -G Ninja ${{ runner.temp }}/glfw-switchfin \
          -DCMAKE_INSTALL_PREFIX=$CMAKE_PREFIX_PATH \
          -DCMAKE_INSTALL_NAME_DIR=$CMAKE_PREFIX_PATH/lib \
          -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=${{ matrix.target }} \
          -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON \
          -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF
        cmake --build build-glfw
        cmake --install build-glfw
    - name: Build mbedtls
      run: |
        curl --retry 5 -sSL https://github.com/Mbed-TLS/mbedtls/releases/download/mbedtls-3.6.2/mbedtls-3.6.2.tar.bz2 | tar jxf - -C ${{ runner.temp }}
        cmake -B build-mbedtls -G Ninja -S ${{ runner.temp }}/mbedtls-3.6.2 \
          -DCMAKE_INSTALL_PREFIX=$CMAKE_PREFIX_PATH \
          -DCMAKE_INSTALL_NAME_DIR=$CMAKE_PREFIX_PATH/lib \
          -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=${{ matrix.target }} \
          -DCMAKE_BUILD_TYPE=Release \
          -DUSE_SHARED_MBEDTLS_LIBRARY=ON \
          -DUSE_STATIC_MBEDTLS_LIBRARY=OFF \
          -DENABLE_PROGRAMS=OFF -DENABLE_TESTING=OFF
        cmake --build build-mbedtls
        cmake --install build-mbedtls
    - name: Build libssh2
      run: |
        curl --retry 5 -sSL https://libssh2.org/download/libssh2-1.11.1.tar.xz | tar Jxf - -C ${{ runner.temp }}
        cmake -B build-libssh2 -G Ninja -S ${{ runner.temp }}/libssh2-1.11.1 \
          -DCMAKE_INSTALL_PREFIX=$CMAKE_PREFIX_PATH \
          -DCMAKE_INSTALL_NAME_DIR=$CMAKE_PREFIX_PATH/lib \
          -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=${{ matrix.target }} \
          -DCMAKE_BUILD_TYPE=Release -DCRYPTO_BACKEND=mbedTLS \
          -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=OFF \
          -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF
        cmake --build build-libssh2
        cmake --install build-libssh2
    - name: Build libcurl
      run: |
        curl --retry 5 -sSL https://curl.se/download/curl-8.11.1.tar.xz | tar Jxf - -C ${{ runner.temp }}
        cmake -B build-curl -G Ninja -S ${{ runner.temp }}/curl-8.11.1 \
          -DCMAKE_INSTALL_PREFIX=$CMAKE_PREFIX_PATH \
          -DCMAKE_INSTALL_NAME_DIR=$CMAKE_PREFIX_PATH/lib \
          -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=${{ matrix.target }} \
          -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON \
          -DHTTP_ONLY=ON -DCURL_DISABLE_PROGRESS_METER=ON -DCURL_USE_SECTRANSP=ON \
          -DBUILD_CURL_EXE=OFF -DUSE_NGHTTP2=OFF -DBUILD_TESTING=OFF -DBUILD_LIBCURL_DOCS=OFF \
          -DUSE_LIBIDN2=OFF -DCURL_USE_LIBSSH2=OFF -DCURL_USE_LIBPSL=OFF
        cmake --build build-curl
        cmake --install build-curl
    - name: Build uchardet
      run: |
        curl --retry 5 -sSL https://www.freedesktop.org/software/uchardet/releases/uchardet-0.0.8.tar.xz | tar Jxf - -C ${{ runner.temp }}
        cmake -B build-uchardet -G Ninja -S ${{ runner.temp }}/uchardet-0.0.8 \
          -DCMAKE_INSTALL_PREFIX=$CMAKE_PREFIX_PATH \
          -DCMAKE_INSTALL_NAME_DIR=$CMAKE_PREFIX_PATH/lib \
          -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=${{ matrix.target }} \
          -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON \
          -DBUILD_BINARY=OFF -DBUILD_STATIC=OFF
        cmake --build build-uchardet
        cmake --install build-uchardet
    - name: Build freetype
      run: |
        curl --retry 5 -sSL https://downloads.sourceforge.net/project/freetype/freetype2/2.13.3/freetype-2.13.3.tar.xz | tar Jxf - -C ${{ runner.temp }}
        meson setup build-freetype ${{ runner.temp }}/freetype-2.13.3 ${{ matrix.meson }} \
          --prefix=$CMAKE_PREFIX_PATH --buildtype=release --default-library=shared \
          -Dharfbuzz=disabled -Dbrotli=disabled -Dzlib=system
        meson compile -C build-freetype
        meson install -C build-freetype
    - name: Build harfbuzz
      run: |
        curl --retry 5 -sSL https://github.com/harfbuzz/harfbuzz/releases/download/10.1.0/harfbuzz-10.1.0.tar.xz | tar Jxf - -C ${{ runner.temp }}
        meson setup build-harfbuzz ${{ runner.temp }}/harfbuzz-10.1.0 ${{ matrix.meson }} \
          --prefix=$CMAKE_PREFIX_PATH --buildtype=release --default-library=shared \
          -Dtests=disabled -Ddocs=disabled -Dicu=disabled -Dcairo=disabled \
          -Dglib=disabled -Dgobject=disabled -Dbenchmark=disabled
        meson compile -C build-harfbuzz
        meson install -C build-harfbuzz
    - name: Build fribidi
      run: |
        curl --retry 5 -sSL https://github.com/fribidi/fribidi/releases/download/v1.0.16/fribidi-1.0.16.tar.xz | tar Jxf - -C ${{ runner.temp }}
        meson setup build-fribidi ${{ runner.temp }}/fribidi-1.0.16 ${{ matrix.meson }} \
          --prefix=$CMAKE_PREFIX_PATH --buildtype=release --default-library=shared \
          -Ddocs=false -Dbin=false -Dtests=false
        meson compile -C build-fribidi
        meson install -C build-fribidi
    - name: Build libass
      run: |
        curl --retry 5 -sSL https://github.com/libass/libass/releases/download/0.17.3/libass-0.17.3.tar.xz | tar Jxf - -C ${{ runner.temp }}
        meson setup build-libass ${{ runner.temp }}/libass-0.17.3 ${{ matrix.meson }} \
          --prefix=$CMAKE_PREFIX_PATH --buildtype=release --default-library=shared
        meson compile -C build-libass
        meson install -C build-libass
    - name: Build dav1d
      run: |
        curl --retry 5 -sSL https://downloads.videolan.org/pub/videolan/dav1d/1.5.0/dav1d-1.5.0.tar.xz | tar Jxf - -C ${{ runner.temp }}
        meson setup build-dav1d ${{ runner.temp }}/dav1d-1.5.0 ${{ matrix.meson }} \
          --prefix=$CMAKE_PREFIX_PATH --buildtype=release --default-library=shared \
          -Denable_tools=false -Denable_examples=false -Denable_tests=false -Denable_docs=false
        meson compile -C build-dav1d
        meson install -C build-dav1d
    - name: Build libwebp
      run: |
        curl --retry 5 -sSL https://github.com/webmproject/libwebp/archive/v1.4.0.tar.gz | tar zxf - -C ${{ runner.temp }}
        cmake -B build-libwebp -G Ninja -S ${{ runner.temp }}/libwebp-1.4.0 \
          -DCMAKE_INSTALL_PREFIX=$CMAKE_PREFIX_PATH \
          -DCMAKE_INSTALL_NAME_DIR=$CMAKE_PREFIX_PATH/lib \
          -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=${{ matrix.target }} \
          -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON \
          -DWEBP_BUILD_EXTRAS=OFF -DWEBP_BUILD_ANIM_UTILS=OFF \
          -DWEBP_BUILD_CWEBP=OFF -DWEBP_BUILD_DWEBP=OFF \
          -DWEBP_BUILD_GIF2WEBP=OFF -DWEBP_BUILD_IMG2WEBP=OFF \
          -DWEBP_BUILD_VWEBP=OFF -DWEBP_BUILD_WEBPINFO=OFF \
          -DWEBP_BUILD_WEBPMUX=OFF -DWEBP_BUILD_LIBWEBPMUX=OFF
        cmake --build build-libwebp
        cmake --install build-libwebp
    - name: Build ffmpeg
      run: |
        curl --retry 5 -sSL https://ffmpeg.org/releases/ffmpeg-7.1.tar.xz | tar Jxf - -C ${{ runner.temp }}
        patch -d ${{ runner.temp }}/ffmpeg-7.1 -Nbp1 -i ${{ github.workspace }}/scripts/mingw64/ffmpeg/avio.patch
        mkdir -p build-ffmpeg && cd build-ffmpeg
        ${{ runner.temp }}/ffmpeg-7.1/configure --enable-shared --disable-static --pkg-config-flags=-static \
          --prefix=$CMAKE_PREFIX_PATH --enable-pthreads --disable-runtime-cpudetect \
          --cc=clang --enable-cross-compile --target-os=darwin --arch=${{ matrix.arch }} \
          --extra-cflags='-arch ${{ matrix.arch }} -mmacosx-version-min=${{ matrix.target }}' \
          --extra-cxxflags='-arch ${{ matrix.arch }} -mmacosx-version-min=${{ matrix.target }}' \
          --extra-ldflags='-arch ${{ matrix.arch }} -mmacosx-version-min=${{ matrix.target }}' \
          --disable-autodetect --disable-encoders --enable-pic ${{ matrix.ffmpeg }} \
          --disable-programs --disable-doc --disable-debug --disable-avdevice --enable-libssh2 \
          --disable-filters --enable-filter=hflip,vflip,transpose --disable-muxers \
          --disable-protocols --enable-protocol=file,http,tcp,udp,hls,https,tls,ftp,libssh2,rtp,crypto,httpproxy \
          --disable-libjack --disable-indev=jack --disable-postproc --enable-network \
          --enable-libdav1d --enable-libass --enable-libfreetype --enable-zlib --enable-bzlib \
          --enable-videotoolbox --enable-audiotoolbox --enable-mbedtls --enable-gpl --enable-version3
        make -j$(sysctl -n hw.ncpu)
        make install
    - name: Build libplacebo
      if: ${{ matrix.tag != 'Intel_Old' }}
      run: |
        git clone https://github.com/haasn/libplacebo.git -b v7.349.0 --depth 1 --recurse-submodules ${{ runner.temp }}/libplacebo
        meson setup build-libplacebo ${{ runner.temp }}/libplacebo ${{ matrix.meson }} \
          --prefix=$CMAKE_PREFIX_PATH --buildtype=release --default-library=shared \
          -Ddemos=false -Dtests=false -Dopengl=enabled -Dlcms=disabled -Dvulkan=disabled
        meson compile -C build-libplacebo
        meson install -C build-libplacebo
    - name: Build mpv
      if: ${{ matrix.tag != 'Intel_Old' }}
      run: |
        curl --retry 5 -sSL https://github.com/mpv-player/mpv/archive/v0.39.0.tar.gz | tar zxf - -C ${{ runner.temp }}
        curl --retry 5 -sSL https://github.com/mpv-player/mpv/commit/901b9bc8888c8bc5647d146aa4b84a9cccc9cbe1.patch | patch -d ${{ runner.temp }}/mpv-0.39.0 -Nbp1 -i -
        meson setup build-mpv ${{ runner.temp }}/mpv-0.39.0 ${{ matrix.meson }} \
          --prefix=$CMAKE_PREFIX_PATH --buildtype=release --default-library=shared \
          -Dlibmpv=true -Dcplayer=false -Dtests=false -Dswift-build=disabled -Dcocoa=disabled \
          -Dmacos-cocoa-cb=disabled -Dmacos-media-player=disabled -Dmacos-touchbar=disabled \
          -Dlibarchive=disabled -Dlcms2=disabled -Djpeg=disabled \
          -Dmanpage-build=disabled -Dhtml-build=disabled 
        meson compile -C build-mpv
        meson install -C build-mpv
    - name: Build mpv36
      if: ${{ matrix.tag == 'Intel_Old' }}
      run: |
        curl --retry 5 -sSL https://github.com/mpv-player/mpv/archive/v0.36.0.tar.gz | tar zxf - -C ${{ runner.temp }}
        patch -d ${{ runner.temp }}/mpv-0.36.0 -Nbp1 -i ${{ github.workspace }}/scripts/macos/mpv.patch
        patch -d ${{ runner.temp }}/mpv-0.36.0 -Nbp1 -i ${{ github.workspace }}/scripts/macos/lavfi.patch
        meson setup build-mpv ${{ runner.temp }}/mpv-0.36.0 ${{ matrix.meson }} \
          --prefix=$CMAKE_PREFIX_PATH --buildtype=release --default-library=shared \
          -Dlibmpv=true -Dcplayer=false -Dtests=false -Dswift-build=disabled \
          -Dmacos-cocoa-cb=disabled -Dmacos-media-player=disabled -Dmacos-touchbar=disabled \
          -Dlibarchive=disabled -Dlcms2=disabled -Djpeg=disabled \
          -Dmanpage-build=disabled -Dhtml-build=disabled 
        meson compile -C build-mpv
        meson install -C build-mpv
    - name: Build packages
      run: |
        cd $CMAKE_PREFIX_PATH
        tar zcf ${{ github.workspace }}/dylib-ffmpeg71-${{ matrix.tag }}.tar.gz \
          include lib/pkgconfig lib/cmake lib/*.dylib
    - name: Archive Build Logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: logs-${{ matrix.tag }}
        path: |
          build-ffmpeg/ffbuild/*.log
          build-*/meson-logs/*.txt
    - name: Upload packages
      uses: softprops/action-gh-release@v2
      with:
        name: macos-dylib
        tag_name: macos-dylib
        prerelease: true
        files: dylib-*.tar.gz
        body: |
          ![download](https://img.shields.io/github/downloads/${{ github.repository }}/macos-dylib/total?label=Downloads)